on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0"

jobs:
    update_icons:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.10'
            - run: python update_icons.py
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Update icons
