on: workflow_dispatch

jobs:
    update_icons:
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: python update_icons.py
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Update icons
